Repository oreumi-dreamer/Dreamer, pull requests merged in 2024-12, with the labels that each got.

#69 꿈 해몽 결과 존재 시 스탬프 추가
  public/images/tomong-stamp-dark.png
  public/images/tomong-stamp.png
  src/app/api/post/feeds/route.js
  src/app/api/post/search/[postId]/route.js
  src/app/api/tomong/read/[postId]/route.js
  src/app/api/tomong/route.js
  src/app/api/tomong/set/[postId]/route.js
  src/app/globals.css
  src/app/tomong/Result.module.css
  src/components/main/MainList.module.css
  src/components/main/Post.jsx
  src/components/modal/PostModal.jsx
  src/components/modal/PostModal.module.css
  src/components/profile/PostList.jsx
  src/components/profile/Profile.module.css
Labels: Publishing, JavaScript

#82 💄 filter color global.css 내 수정 및 다크모드 적용
  src/app/globals.css
Labels: Publishing

#83 피드 API의 isMyself 필드 추가 외
  src/app/api/post/feeds/route.js
  src/components/login/EmailSignup.jsx
  src/components/signup/BasicInfoForm.jsx
  src/components/signup/BasicInfoForm.module.css
Labels: API integration, Publishing, JavaScript

#84 drop-down 임시적용속성 삭제
  src/components/dropDown/DropDown.module.css
  src/components/header/NarrowHeader.module.css
  src/components/header/WideHeader.module.css
Labels: Publishing

#86 프로필 API 수정 외 3건
  src/app/api/post/read/[userId]/route.js
  src/components/modal/CommentArticles.jsx
  src/components/modal/PostModal.jsx
  src/components/post/Post.jsx
  src/components/profile/ProfileInfo.jsx
  src/components/write/WritePost.jsx
Labels: bug, API integration, Publishing

#87 [Signup page, Login page] dark 모드 색상 적용
  src/app/globals.css
  src/app/page.module.css
  src/components/Controls.module.css
  src/components/login/SocialLogin.module.css
  src/components/signup/BasicInfoForm.module.css
  src/components/signup/ProfileForm.module.css
  src/components/signup/SignupHeader.module.css
Labels: Publishing

#89 토몽 스탬프 추가 외 1건
  src/app/tomong/Tomong.module.css
  src/app/tomong/page.js
  src/components/header/WideHeader.module.css
  src/components/tomong/TomongListItem.jsx
Labels: bug, Publishing, JavaScript

#91 배경 스크롤/모달 닫을 때 새로고침/오타 수정/오류 수정
  src/components/profile/Profile.jsx
  src/components/write/HashtagModal.jsx
  src/components/write/MoodModal.jsx
  src/components/write/WritePost.jsx
  src/components/write/WritePost.module.css
Labels: bug, JavaScript

#94 오타 수정, 기능 수정, 주석 삭제
  src/components/write/HashtagModal.jsx
  src/components/write/MoodModal.jsx
  src/components/write/WritePost.jsx
Labels: bug, JavaScript

#95 [login page, signup page] dark mode btn style 수정
  src/app/globals.css
  src/components/Controls.module.css
  src/components/login/SocialLogin.module.css
Labels: Publishing

#100 ✨ [Add] PostContent의 비밀글변경 토글버튼 기능 추가
  src/components/dropDown/DropDown.jsx
  src/components/post/PostContent.jsx
Labels: API integration, JavaScript

#104 💄 댓글 작성 중 모달 나가기 또는 딤드 클릭 시 confirm 을 기본 window 에서 컴포넌트 디자인으로 수정
  src/components/modal/PostModal.jsx
Labels: Publishing

#105 피드 API 수정, 토몽 다크 모드 추가 외 2건
  src/app/api/post/feeds/route.js
  src/app/layout.js
  src/app/tomong/Tomong.module.css
  src/app/tomong/page.js
  src/components/modal/PostModal.module.css
  src/components/post/PostContent.jsx
  src/components/theme/ThemeHandler.jsx
Labels: bug, API integration, Publishing, JavaScript

#108 ✨ 더보기 모달 내 삭제하기 버튼 클릭 시 게시물 삭제되는 기능 적용
  src/components/dropDown/DropDown.jsx
  src/components/main/Post.jsx
Labels: API integration, JavaScript

#111 🎨 props 값 변경으로 사용 변수 제거 및 수정
  src/components/dropDown/DropDown.jsx
Labels: bug, JavaScript

#115 변경된 API 적용
  src/app/api/post/feeds/route.js
  src/components/main/Post.jsx
Labels: API integration

#119 공유 모달 기능 적용 및 토몽 이미지 추가
  public/images/close-without-padding.svg
  public/images/ios-share-circle.svg
  public/images/tomong-hi-480p.png
  public/images/tomong-hi.png
  src/app/tomong/Tomong.module.css
  src/app/tomong/page.js
  src/components/Controls.jsx
  src/components/Controls.module.css
  src/components/main/Post.jsx
  src/components/post/PostContent.jsx
Labels: Publishing, JavaScript

#124 이메일로 로그인 페이지 Figma 디자인 css 적용
  README.md
  src/app/page.module.css
  src/app/tomong/page.js
  src/components/Controls.jsx
  src/components/Controls.module.css
  src/components/login/EmailSignup.jsx
  src/components/login/SocialLogin.jsx
  src/components/login/SocialLogin.module.css
  src/components/signup/BasicInfoForm.jsx
Labels: Publishing, JavaScript

#126 [Email Signup] 이메일 회원가입 css 적용
  src/app/globals.css
  src/components/Controls.jsx
  src/components/login/EmailSignup.jsx
  src/components/login/EmailSignup.module.css
Labels: Publishing

#133 [Email Signup] 이메일 회원가입 css 세부 조정
  src/components/Controls.module.css
  src/components/login/EmailSignup.jsx
  src/components/login/EmailSignup.module.css
Labels: Publishing

#134 팔로우 및 팔로워 모달 적용 및 PNG 배경 색 문제 수정
  src/app/api/account/avatar/route.js
  src/app/api/account/followers/[userId]/route.js
  src/app/api/post/create/route.js
  src/app/api/post/update/[postId]/route.js
  src/app/reset.css
  src/app/signup/page.js
  src/app/tomong/page.js
  src/components/Controls.jsx
  src/components/Controls.module.css
  src/components/main/MainList.jsx
  src/components/profile/ProfileInfo.jsx
  src/lib/api/avatar.js
Labels: bug, API integration, Publishing, JavaScript

#139 사용자 경험 개선 및 버그 수정
  src/app/api/post/create/route.js
  src/components/main/Post.jsx
  src/components/post/PostContent.jsx
  src/components/write/WritePost.jsx
Labels: bug, API integration, JavaScript

#140 모바일 헤더 스타일 관련 수정
  src/app/globals.css
  src/components/header/NarrowHeader.jsx
  src/components/header/NarrowHeader.module.css
  src/utils/calculateModalPosition.js
Labels: Publishing

#141 🎨 이메일로 회원가입 validation 적용
  src/components/Controls.jsx
  src/components/login/EmailSignup.jsx
  src/components/login/EmailSignup.module.css
  src/components/login/SocialLogin.jsx
Labels: Publishing, JavaScript

#143 💄 디자인 수정으로 로그인 기능 제거 및 메인으로 돌아가기 버튼 기능 추가
  src/components/signup/BasicInfoForm.jsx
  src/components/signup/BasicInfoForm.module.css
Labels: Publishing, JavaScript

#146 💄 [Email Login, Signup page] dark mode 색상 적용
  src/components/Controls.module.css
  src/components/login/SocialLogin.module.css
  src/components/signup/BasicInfoForm.module.css
Labels: Publishing

#148 🐛 댓글 작성 여러번 클릭 시 모두 댓글 등록되는 부분 수정
  src/components/post/PostContent.jsx
Labels: bug, JavaScript

#149 글작성 업로드: 로딩바 컴포넌트 제작
  public/images/pencil.svg
  src/components/write/Uploading.jsx
  src/components/write/Uploading.module.css
  src/components/write/WritePost.module.css
Labels: Publishing

#151 💄 토몽 AI dark mode css 수정
  src/app/globals.css
  src/app/tomong/Tomong.module.css
Labels: Publishing

#154 🐛 해몽 꿈 선택 및 해몽된 꿈목록 레이아웃 어긋나는 문제 수정
  src/app/tomong/Tomong.module.css
Labels: bug, Publishing

#156 🐛 피드에서 더 보기 버튼을 클릭한 이후 나오는 게시글이 클릭되지 않는 문제 수정
  src/components/main/MainList.jsx
  src/components/main/Post.jsx
Labels: bug

#157 💄 [PostModal] 댓글 작성 후 로딩 아이콘 위치 조정
  src/components/Loading.jsx
  src/components/modal/PostModal.module.css
  src/components/post/PostContent.jsx
Labels: Publishing

#159 토몽 예외 처리 및 모달 충돌 수정
  src/app/[id]/page.js
  src/app/tomong/page.js
  src/components/header/Header.jsx
  src/components/profile/Profile.jsx
Labels: bug, JavaScript

#160 메타데이터 적용 및 게시글 작성 경험 개선
  src/app/[id]/page.js
  src/app/privacy/page.js
  src/app/terms/page.js
  src/app/tomong/page.js
  src/components/post/PostContent.jsx
  src/components/profile/Profile.jsx
  src/components/tomong/Result.module.css
  src/components/tomong/Tomong.jsx
  src/components/tomong/Tomong.module.css
  src/components/write/WritePost.jsx
Labels: JavaScript

#169 💄 [Email Login page] 사용자 경험 개선을 위한 validation 수정 및 로그인 버튼 클릭 시 로딩 적용
  .github/workflows/main.yml
  src/app/join/verify-email/page.js
  src/app/join/verify-email/page.module.css
  src/components/login/SocialLogin.jsx
  src/components/login/SocialLogin.module.css
Labels: Publishing, JavaScript

#170 반응형 레이아웃 개선
  public/images/loading-spinner.svg
  src/app/globals.css
  src/app/layout.js
  src/app/privacy/page.module.css
  src/components/Loading.jsx
  src/components/Loading.module.css
  src/components/NavProvider.js
  src/components/main/MainList.module.css
  src/components/main/Post.jsx
  src/components/modal/PostModal.module.css
  src/components/profile/Profile.module.css
Labels: Publishing

#171 🔥 이메일로 회원가입 페이지 분리로 css 미사용 코드 삭제
  src/app/join/page.module.css
Labels: Publishing

#178 [Signup] 모바일 css 적용
  src/app/join/page.module.css
  src/app/page.module.css
  src/app/signup/page.module.css
  src/components/login/SocialLogin.module.css
  src/components/signup/BasicInfoForm.module.css
  src/components/signup/ProfileForm.module.css
  src/components/signup/SignupHeader.jsx
  src/components/signup/SignupHeader.module.css
Labels: Publishing

#179 [Signup page] 회원가입 라우터 분리되어 다크모드 미적용된 부분 수정
  src/app/globals.css
  src/app/join/page.module.css
  src/components/login/EmailSignup.module.css
  src/components/login/SocialLogin.module.css
Labels: Publishing

#180 반응형 디자인 개선
  src/app/globals.css
  src/components/Loading.module.css
  src/components/NavProvider.js
  src/components/header/NarrowHeader.module.css
  src/components/main/MainList.module.css
  src/components/main/Post.jsx
  src/components/modal/PostModal.module.css
Labels: Publishing

#181 프로필 페이지 포스트 레이아웃 재정비
  src/app/globals.css
  src/components/Controls.module.css
  src/components/profile/Profile.module.css
  src/components/write/WritePost.jsx
Labels: Publishing

#183 토몽 관련 반응형 레이아웃 적용
  src/app/globals.css
  src/components/tomong/Tomong.jsx
  src/components/tomong/Tomong.module.css
Labels: Publishing

#192 💄 [Email Login, Email Signup] 모바일 css 적용
  src/app/join/page.module.css
  src/app/signup/page.module.css
  src/components/login/EmailSignup.module.css
  src/components/login/SocialLogin.jsx
  src/components/login/SocialLogin.module.css
Labels: Publishing

#193 💄 global.css body padding 수정으로 login-title 클래스가 있는 경우 body padding에 important 추가
  src/app/join/page.module.css
  src/app/signup/page.module.css
  src/components/login/SocialLogin.module.css
Labels: Publishing

#196 다크 모드 UI 개선 및 isPrivate 버그 수정
  src/app/api/post/read/[userId]/route.js
  src/app/globals.css
Labels: API integration, Publishing, JavaScript

#197 🐛 이메일 회원가입 중 이메일 로그인 버튼 클릭 오류 수정
  src/components/login/EmailSignup.jsx
Labels: bug, JavaScript

#198 🎨 [Profile edit] 이름/아이디 최대글자 validation 설정
  src/components/Controls.jsx
  src/components/profile/ProfileEdit.jsx
Labels: JavaScript

#200 회원 가입 로직 변경 및 스타일 수정
  package-lock.json
  package.json
  src/app/api/auth/check-email-verification/route.js
  src/app/api/auth/send-email-verification/route.js
  src/components/Controls.module.css
  src/components/login/EmailSignup.jsx
  src/components/login/EmailSignup.module.css
Labels: API integration, Publishing, JavaScript

#202 🐛 닫기 버튼 이미지를 찾지 못하는 문제 수정
  src/components/signup/ProfileForm.jsx
Labels: bug

#203 🐛 아이디, 닉네임이 긴 사용자 PostModal 내 글자 수 제한 표기
  src/app/signup/page.js
  src/components/login/SocialLogin.jsx
  src/components/modal/CommentArticles.jsx
  src/components/modal/CommentArticles.module.css
  src/components/modal/PostModal.module.css
  src/components/post/PostContent.jsx
  src/components/signup/BasicInfoForm.jsx
Labels: bug, Publishing

#209 사용자 프로필 경로 수정 외 1건
  src/app/globals.css
  src/app/users/[id]/page.js
  src/components/Controls.jsx
  src/components/error404/Error404.jsx
  src/components/footer/Recommends.jsx
  src/components/header/NarrowHeader.jsx
  src/components/header/WideHeader.jsx
  src/components/main/Post.jsx
  src/components/modal/CommentArticles.jsx
  src/components/post/PostContent.jsx
  src/components/profile/ProfileEdit.jsx
  src/components/tomong/Tomong.jsx
  src/components/tomong/Tomong.module.css
  src/components/write/WritePost.jsx
Labels: Publishing, JavaScript

#210 커스텀 스크롤 바 수정 및 셀렉트 박스에 커스텀 스크롤 바 적용
  src/components/Controls.jsx
  src/components/Controls.module.css
Labels: Publishing, JavaScript

#213 Footer 관련 레이아웃 수정
  src/app/globals.css
  src/components/footer/Footer.module.css
Labels: Publishing

#218 Signup 페이지 반응형 대응
  src/app/globals.css
  src/app/signup/page.module.css
  src/components/signup/BasicInfoForm.jsx
  src/components/signup/BasicInfoForm.module.css
  src/components/signup/ProfileForm.module.css
Labels: Publishing

#221 반응형 레이아웃 수정 및 계정 설정 페이지 구현
  src/app/account/Account.module.css
  src/app/account/modify-email/ModifyEmail.module.css
  src/app/account/modify-email/page.js
  src/app/account/modify-password/ModifyPassword.module.css
  src/app/account/modify-password/page.js
  src/app/account/page.js
  src/app/api/auth/check-email/route.js
  src/app/api/auth/update-email/route.js
  src/app/api/auth/withdraw/route.js
  src/app/globals.css
  src/components/Controls.jsx
  src/components/Controls.module.css
  src/components/auth/AuthStateHandler.jsx
  src/components/header/NarrowHeader.module.css
  src/components/profile/Profile.module.css
  src/utils/auth/updateEmail.js
  src/utils/auth/verifyPassword.js
Labels: API integration, Publishing, JavaScript, Deploy

#222 회원 정보 페이지에서 Google로 로그인을 인식하지 못하는 문제 수정 외 2건
  src/app/account/page.js
  src/components/auth/AuthStateHandler.jsx
  src/components/login/SocialLogin.jsx
Labels: bug, Publishing

#223 [Signup] 이메일 회원가입 css 세부 조정
  src/app/signup/page.module.css
  src/components/login/EmailSignup.module.css
Labels: Publishing

#225 게시글 수정 기능 구현
  src/components/dropDown/DropDown.jsx
  src/components/main/Post.jsx
  src/components/post/PostContent.jsx
  src/components/profile/PostList.jsx
  src/components/write/HashtagModal.jsx
  src/components/write/MoodModal.jsx
  src/components/write/WritePost.jsx
Labels: Publishing, JavaScript

#226 WritePost 반응형 추가
  src/components/write/WritePost.jsx
  src/components/write/WritePost.module.css
Labels: Publishing

#229 🎨 회원가입 중 중복 아이디 체크 validation 추가
  src/components/signup/BasicInfoForm.jsx
Labels: Publishing, JavaScript

#230 신고 기능 추가 외 1건
  src/app/api/report/route.js
  src/components/Controls.jsx
  src/components/Controls.module.css
  src/components/dropDown/DropDown.jsx
  src/components/header/HeaderModal.jsx
  src/components/main/Post.jsx
  src/components/post/PostContent.jsx
  src/components/profile/PostList.jsx
  src/components/profile/ProfileEdit.jsx
  src/components/report/Report.jsx
Labels: Publishing, JavaScript

#231 🔧 ReportModal 경로 대소문자 수정
  src/components/main/Post.jsx
Labels: bug, Deploy

#232 🐛 회원가입 다크모드 선택 시 적용되지 않는 버그 수정
  src/components/signup/ProfileForm.jsx
Labels: bug, JavaScript

#235 🐛 commentsCount 필드 값이 실제 댓글 데이터와 차이가 있는 문제 수정
  src/app/api/post/feeds/route.js
  src/app/api/post/read/[userId]/route.js
  src/app/api/post/search/[postId]/route.js
Labels: bug

#239 [PostModal] 반응형 수정 및 모바일 css 적용
  src/components/modal/CommentArticles.jsx
  src/components/modal/CommentArticles.module.css
  src/components/modal/PostModal.module.css
Labels: bug, Publishing

#242 🐛[Prodile Edit] id 유효성검사 추가 적용 및 기존 유효성 검사코드 수정
  src/components/profile/ProfileEdit.jsx
Labels: bug, JavaScript

#243 비밀번호 찾기 기능 추가
  src/app/api/auth/check-email/route.js
  src/app/api/auth/reset-password/route.js
  src/app/join/page.module.css
  src/components/login/FindPassword.jsx
  src/components/login/SocialLogin.jsx
  src/components/login/SocialLogin.module.css
  src/utils/validation.js
Labels: API integration, Publishing, JavaScript

#244 글작성 모달 반응형 css 추가
  src/components/write/WritePost.jsx
  src/components/write/WritePost.module.css
Labels: documentation, Publishing, JavaScript

#246 🐛 [PostModal] 아이디/닉네임 글자 수가 긴 경우 css 수정
  src/components/modal/CommentArticles.jsx
  src/components/modal/CommentArticles.module.css
  src/components/modal/PostModal.module.css
  src/components/post/PostContent.jsx
  src/components/profile/ProfileEdit.jsx
Labels: bug, Publishing, JavaScript

#248 [PostModal] 반응형 css 어긋나는부분 세부 수정
  src/components/modal/CommentArticles.jsx
  src/components/modal/CommentArticles.module.css
  src/components/post/PostContent.jsx
Labels: bug, Publishing

#250 [Profile] 페이지 레이아웃 벗어남 / Footer 겹침 css 수정
  src/components/profile/Profile.module.css
Labels: bug, Publishing

#251 팔로워 모달 버그 수정 외 2건
  public/robots.txt
  src/app/sitemap.js
  src/components/Controls.jsx
  src/components/header/NarrowHeader.module.css
Labels: bug, Publishing, JavaScript

#253 [Profile Edit]💄 이름, 아이디 validation 문구 적용
  src/components/profile/Profile.module.css
  src/components/profile/ProfileEdit.jsx
Labels: Publishing

#254 배포 환경에서의 토몽 오류 해결 외 1건
  src/app/alarm/page.js
  src/app/api/tomong/route.js
  src/app/debug/posting/[postId]/page.js
  src/app/debug/posting/page.js
  src/app/debug/posting/page.module.css
  src/app/debug/posts/[userId]/page.js
  src/app/debug/posts/[userId]/page.module.css
  src/app/debug/posts/page.js
  src/app/debug/posts/page.module.css
  src/app/debug/user-modify/page.js
  src/app/debug/user-modify/page.module.css
  src/app/reset.css
  src/app/search/page.js
  src/app/search/page.module.css
  src/components/Controls.module.css
  src/components/debug/Comments.jsx
  src/components/debug/Comments.module.css
  src/components/modal/PostModal.jsx
  src/components/profile/Profile.module.css
  src/components/profile/ProfileInfo.jsx
  src/components/tomong/Tomong.jsx
  src/components/write/WritePost.jsx
Labels: bug, API integration, Publishing, JavaScript

#255 [PostModal] 본문 title이 길 때 보이지 않는 bug 수정
  src/components/modal/CommentArticles.jsx
  src/components/modal/PostModal.module.css
Labels: bug, Publishing

#257 [Signup] 프로필 사진 파일 첨부 조건 적용
  src/components/signup/ProfileForm.jsx
  src/components/signup/SignupHeader.module.css
Labels: Publishing

#258 💄 globalcss img 속성 적용으로 object-fit 일괄 적용
  src/components/modal/PostModal.module.css
  src/components/profile/Profile.module.css
Labels: bug, Publishing

#259 💄 globalcss img 속성 적용으로 object-fit 적용
  src/components/main/MainList.module.css
Labels: bug, Publishing

#260 💄 button hover, active 추가 적용 / ♻️ global css 관련 코드 리팩토링 적용
  src/app/globals.css
  src/components/Controls.module.css
  src/components/error404/Error404.module.css
  src/components/header/NarrowHeader.module.css
  src/components/login/EmailSignup.module.css
  src/components/login/SocialLogin.module.css
Labels: Publishing, Global operations

#261 접근성 및 반응형 레이아웃 개선
  src/app/account/Account.module.css
  src/app/account/modify-email/ModifyEmail.module.css
  src/app/account/page.js
  src/app/api/auth/check-email-verification/route.js
  src/app/globals.css
  src/app/join/page.module.css
  src/app/page.module.css
  src/app/signup/page.module.css
  src/components/Controls.jsx
  src/components/Controls.module.css
  src/components/Loading.module.css
  src/components/dropDown/DropDown.jsx
  src/components/footer/Recommends.jsx
  src/components/header/NarrowHeader.jsx
  src/components/header/WideHeader.jsx
  src/components/login/EmailSignup.jsx
  src/components/login/EmailSignup.module.css
  src/components/login/SocialLogin.jsx
  src/components/login/SocialLogin.module.css
  src/components/main/Post.jsx
  src/components/modal/CommentArticles.jsx
  src/components/modal/PostModal.jsx
  src/components/post/PostContent.jsx
  src/components/profile/PostCard.jsx
  src/components/profile/PostList.jsx
  src/components/profile/Profile.module.css
  src/components/profile/ProfileEdit.jsx
  src/components/profile/SparkButton.jsx
  src/components/signup/BasicInfoForm.module.css
  src/components/signup/ProfileForm.jsx
  src/utils/postTime.js
Labels: Publishing, JavaScript

#262 반응형 레이아웃 및 접근성 개선
  src/app/globals.css
  src/app/signup/page.js
  src/components/Controls.jsx
  src/components/Loading.jsx
  src/components/Loading.module.css
  src/components/dropDown/DropDown.jsx
  src/components/footer/Recommends.jsx
  src/components/header/NarrowHeader.jsx
  src/components/header/WideHeader.module.css
  src/components/main/MainList.jsx
  src/components/main/Post.jsx
  src/components/modal/CommentArticles.jsx
  src/components/modal/PostModal.jsx
  src/components/modal/PostModal.module.css
  src/components/post/PostContent.jsx
  src/components/profile/PostCard.jsx
  src/components/profile/PostList.jsx
  src/components/profile/Profile.module.css
  src/components/profile/ProfileInfo.jsx
  src/components/report/Report.jsx
  src/components/tomong/Tomong.jsx
  src/components/tomong/Tomong.module.css
  src/components/write/WritePost.jsx
  src/utils/scrollHandler.js
Labels: Publishing, JavaScript

#264 검색 기능 추가
  src/app/api/post/search/route.js
  src/app/search/Search.module.css
  src/app/search/page.js
  src/app/search/page.module.css
  src/components/Controls.jsx
  src/components/Controls.module.css
  src/components/main/MainList.module.css
  src/components/main/Post.jsx
  src/components/main/Post.module.css
  src/components/report/Report.jsx
  src/utils/highlightText.js
Labels: API integration, Publishing, JavaScript

#265 프로필에서 팔로잉 카운트 즉각 반영 외 1건
  src/app/api/auth/verify/route.js
  src/components/Controls.jsx
  src/components/footer/Recommends.jsx
  src/components/profile/ProfileInfo.jsx
  src/store/store.js
  src/utils/auth/checkUser.js
Labels: JavaScript, Deploy

#267 🐛 [Header] 모바일 환경에서 PostModal 띄울 때 헤더바 사라지는 Error 수정
  src/components/header/NarrowHeader.module.css
Labels: bug, Publishing

#269 🐛 PostModal 띄울 때 footer가 상단으로 올라가는 bug 수정
  src/app/globals.css
Labels: bug, Publishing

#271 🎨 게시글의 작성자가 타인 댓글 삭제 가능하도록 기능 추가
  src/app/api/comment/delete/[postId]/route.js
Labels: JavaScript

#272 반응형 레이아웃 개선 및 검색 버그 수정
  src/app/api/post/search/route.js
  src/app/globals.css
  src/app/layout.js
  src/app/page.module.css
  src/app/search/Search.module.css
  src/components/main/Post.jsx
  src/components/modal/PostModal.module.css
  src/components/profile/Profile.module.css
  src/components/write/WritePost.jsx
  src/components/write/WritePost.module.css
Labels: Publishing, JavaScript

#273 모달에서 게시글 상태 변화 시 상위 컴포넌트의 리스트에 반영되도록 수정
  src/app/search/page.js
  src/components/main/MainList.jsx
  src/components/main/Post.jsx
  src/components/modal/CommentArticles.jsx
  src/components/modal/PostModal.jsx
  src/components/modal/PostModal.module.css
  src/components/post/PostContent.jsx
  src/components/profile/Profile.jsx
Labels: JavaScript

#274 피드 알고리즘 개선 외 2건
  src/app/api/post/feeds/route.js
  src/components/main/MainList.jsx
  src/components/report/Report.jsx
Labels: bug, API integration, JavaScript

#275 프로필 수정 및 ProfileForm 다음 버튼 css 수정
  src/components/profile/Profile.module.css
  src/components/profile/ProfileEdit.jsx
  src/components/signup/ProfileForm.jsx
  src/components/signup/ProfileForm.module.css
Labels: Publishing

#277 🎨 비밀번호 input 및 비밀번호 찾기 버튼 유효성 검사 관련 disabled 적용
  src/components/login/FindPassword.jsx
Labels: Publishing, JavaScript

#279 [Post Modal] title이 없는 경우 날짜 + 꿈일기 표기되도록 예외 처리
  src/components/post/PostContent.jsx
Labels: bug, JavaScript

#281 🐛 비밀번호 변경 다크모드 컬러 적용 안되는 bug 수정 완료
  src/app/account/modify-password/ModifyPassword.module.css
Labels: bug, Publishing

#282 💄 iOS Safari에서 모달을 터치하고 나갔을 때 포커스 아웃라인이 잘리는 문제 수정
  src/app/api/account/modify/route.js
  src/app/api/auth/update-email/route.js
  src/app/api/comment/create/[postId]/route.js
  src/app/api/comment/delete/[postId]/route.js
  src/app/api/comment/read/[postId]/route.js
  src/app/api/join/check-userid/route.js
  src/app/api/post/feeds/route.js
  src/app/api/post/spark/[postId]/route.js
  src/app/api/post/update/[postId]/route.js
  src/app/api/tomong/streaming-token/route.js
  src/components/main/MainList.module.css
Labels: Publishing

#283 글작성 모달 textarea 높이 변화 추가
  src/components/write/WritePost.jsx
  src/components/write/WritePost.module.css
Labels: JavaScript

#284 반응형 레이아웃 수정, 모달 버그 수정 및 유저 프로필 접근 권한 수정
  src/app/globals.css
  src/components/Controls.module.css
  src/components/auth/AuthStateHandler.jsx
  src/components/modal/PostModal.jsx
  src/components/modal/PostModal.module.css
Labels: Publishing, JavaScript

#285 💄 PostModal의 댓글 입력 레이아웃 조정
  src/components/modal/PostModal.module.css
Labels: Publishing

#286 iOS Safari에서 의도하지 않게 모달이 표시되는 문제 수정
  src/app/layout.js
  src/components/modal/PostModal.module.css
Labels: Publishing

#287 자기 자신의 게시글의 더 보기 버튼 중 '삭제하기' 버튼이 눌리지 않는 문제 수정
  src/components/modal/PostModal.module.css
Labels: bug, Publishing

#288 /terms와 /privacy에 스크롤 바가 두 번 생기는 문제 수정
  src/app/globals.css
Labels: bug, Publishing
